FROM postgres:latest

ENV POSTGRES_USER postgres_admin
ENV POSTGRES_PASSWORD AAaa@@11
ENV POSTGRES_DB revision-db
#COPY ./apps/postgres/init.sql /docker-entrypoint-initdb.d/
#RUN dotnet ef migrations add InitialCreate
#RUN dotnet ef database update
